# Official DTU colors for plots
colors:
  dtu_red: "#990000"
  black: "#000000"
  blue: "#2F3EEA"
  bright_green: "#1FD082"
  navy_blue: "#030F4F"
  yellow: "#F6D04D"
  orange: "#FC7634"
  pink: "#F7BBB1"
  grey: "#DADADA"
  red: "#E83F48"
  green: "#008835"
  purple: "#79238E"

# Sample frequency of the data
sample_frequency: 500

# All electrode information
electrodes:
  all_electrodes_arranged: [
    'Fp1-A1', 'Fpz-A1', 'Fp2-A2', 'F7-A1', 'F3-A1', 'Fz-A1', 'F4-A2', 'F8-A2', 'FT7-A1', 'FC3-A1', 'FCz-A1', 'FC4-A2',
    'FT8-A2', 'C3-A1', 'Cz-A2', 'C4-A2', 'T4-A2', 'TP7-A1', 'CP3-A1', 'CPz-A2', 'CP4-A2', 'TP8-A2', 'T5-A1', 'P3-A1',
    'Pz-A2', 'P4-A2', 'T6-A2', 'O1-A1', 'Oz-A2', 'O2-A2',
  ]
  # Chosen electrodes are 19 (18 because T3 is missing) to reduce dimensionality
  # The "basic" 10-20 system
  # Based on papers:
  # An Optimal Channel Selection for EEG-Based Depression Detection via Kernel-Target Alignment
  # Electroencephalogram (EEG)-based computer-aided technique to diagnose major depressive disorder (MDD)
  # -------> Tried using only these and classification got worse...
  chosen_electrodes: [
    'Fp1-A1', 'Fpz-A1', 'Fp2-A2', 'F7-A1', 'F3-A1', 'Fz-A1', 'F4-A2', 'F8-A2', 'C3-A1', 'Cz-A2', 'C4-A2', 'T4-A2',
    'T5-A1', 'P3-A1', 'Pz-A2', 'P4-A2', 'T6-A2', 'O1-A1', 'O2-A2',
  ]
  frontal: [
    'Fp1-A1', 'Fpz-A1', 'Fp2-A2', 'F7-A1', 'F3-A1', 'Fz-A1', 'F4-A2', 'F8-A2'
  ]
  temporal: [
    'T4-A2', 'TP7-A1', 'TP8-A2', 'T5-A1'
  ]
  parietal: [
    'P3-A1', 'Pz-A2', 'P4-A2',
  ]
  occipital: [
    'O1-A1', 'Oz-A2', 'O2-A2'
  ]
  central: [
    'C3-A1', 'Cz-A2', 'C4-A2'
  ]
  reference_electrodes:
    A1ref: [
      "F7", "FT7", "T3", "TP7", "T5", "Fp1", "F3", "FC3", "C3", "CP3", "P3", "O1", "Fpz", "Fz", "FCz"
    ]
    A2ref: [
      "Cz", "CPz", "Pz", "Oz", "Fp2", "F4", "FC4", "C4", "CP4", "P4", "O2", "F8", "FT8", "T4", "TP8", "T6"
    ]

# Second round of data obtained
new_data: [
  "S51", "S52", "S53", "S54", "S55", "S56", "S57", "S58", "S59", "S60", "S61"
]

# Classification of subjects
subject_classes:
  healthy: [
    "S2", "S3", "S9", "S10", "S12", "S13", "S14", "S15", "S19", "S20", "S24", "S25", "S30", "S32", "S38", "S39", "S42",
    "S46", "S29", "S6", "S23", "S47", "S49", "S53", "S55", "S56", "S57", "S60", "S61"
  ]
  depressed_active: [
    "S1", "S4", "S5", "S7", "S8", "S11", "S16", "S17", "S18", "S21", "S22", "S26", "S27", "S51", "S52", "S54", "S58",
    "S59"
  ]
  depressed_sham: [
    "S31", "S33", "S35", "S36", "S37", "S40", "S41", "S43", "S44", "S45"
  ]
  healthy_num: [
    2, 3, 9, 10, 12, 13, 14, 15, 19, 20, 24, 25, 30, 32, 38, 39, 42, 46, 29, 6, 23, 47, 49, 53, 55, 56, 57, 60, 61
  ]
  depressed_num: [
    1, 4, 5, 7, 8, 11, 16, 17, 18, 21, 22, 26, 27, 51, 52, 54, 58, 59, 31, 33, 35, 36, 37, 40, 41, 43, 44, 45
  ]

# Noisy records which should be removed and not used
noisy_recs: [
    "S1_pre_EC_DepActive_116s.txt", "S8_post_EC_DepActive_116s.txt", "S9_post_EC_Healthy_116s.txt",
    "S9_pre_EC_Healthy_116s.txt", "S9_pre_EO_Healthy_116s.txt", "S15_pre_EC_Healthy_116s.txt",
    "S15_pre_EO_Healthy_116s.txt", "S24_pre_EO_Healthy_116s.txt", "S29_post_EC_Healthy_116s.txt",
    "S29_post_EO_Healthy_116s.txt", "S33_post_EC_DepSham_116s.txt", "S35_pre_EO_DepSham_116s.txt",
    "S35_pre_EC_DepSham_116s.txt", "S35_post_EO_DepSham_116s.txt", "S35_post_EC_DepSham_116s.txt",
    "S37_pre_EO_DepSham_116s.txt", "S37_pre_EC_DepSham_116s.txt", "S39_post_EC_Healthy_116s.txt",
    "S39_post_EO_Healthy_116s.txt", "S39_pre_EC_Healthy_116s.txt", "S40_post_EC_DepSham_116s.txt",
    "S40_post_EO_DepSham_116s.txt", "S40_pre_EC_DepSham_116s.txt", "S41_post_EC_DepSham_116s.txt",
    "S41_post_EO_DepSham_116s.txt", "S41_pre_EC_DepSham_116s.txt", "S42_post_EC_Healthy_116s.txt",
    "S42_pre_EO_Healthy_116s.txt", "S42_pre_EC_Healthy_116s.txt", "S44_post_EC_DepSham_116s.txt",
    "S44_post_EO_DepSham_116s.txt", "S45_pre_EC_DepSham_116s.txt", "S45_pre_EO_DepSham_116s.txt",
    "S45_post_EC_DepSham_116s.txt", "S45_post_EO_DepSham_116s.txt", "S46_post_EO_Healthy_116s.txt",
    "S46_pre_EO_Healthy_116s.txt", "S46_pre_EC_Healthy_116s.txt", "S47_pre_EO_Healthy_116s.txt",
    "S47_pre_EC_Healthy_116s.txt", "S52_pre_EC_DepActive_116s.txt"
]