colors:
  dtu_red: "#990000"
  white: "#ffffff"
  black: "#000000"
  blue: "#2F3EEA"
  bright_green: "#1FD082"
  navy_blue: "#030F4F"
  yellow: "#F6D04D"
  orange: "#FC7634"
  pink: "#F7BBB1"
  grey: "#DADADA"
  red: "#E83F48"
  green: "#008835"
  purple: "#79238E"